name: Identity Functional Tests Run
# TODO: https://github.com/Tyrrrz/GitHubActionsTestLogger
on:
  workflow_dispatch:
  push:
    #branches:
    #  - develop
  pull_request:
    branches:
      - develop

jobs:
  run-auth-integration-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      Test_Project_Path: src/Services/Identity/Identity.Functional.Tests/Identity.Functional.Tests.csproj
      Docker_Compose_Path: "src/Services/Identity/Identity.Functional.Tests/docker-compose.yml"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Start dependencies (docker-compose)
        run: |
          docker-compose -f ${{ env.Docker_Compose_Path }} up -d --build

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Add guthub packages as source
        run: dotnet nuget add source --username "IvayloGugalov" --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name git "https://nuget.pkg.github.com/IvayloGugalov/index.json"

      - name: Build
        run: dotnet build ${{ env.Test_Project_Path }} --configuration Debug
    
      - name: Test
        run: dotnet test ${{ env.Test_Project_Path }} --configuration Debug

      - name: Stop containers
        if: always()
        run: docker-compose -f ${{ env.Docker_Compose_Path }} down