on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-auth-integration-tests:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      Test_Project_Path: src/Services/Identity/Identity.FunctionalTests/Identity.FunctionalTests.csproj
      Docker_Compose_Path: "src/Services/Identity/Identity.FunctionalTests/docker-compose.yml"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Start dependencies (docker-compose)
        run: |
          docker-compose -f ${{ env.Docker_Compose_Path }} up -d --build

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build ${{ env.Test_Project_Path }} --configuration Debug
    
      - name: Test
        run: dotnet test ${{ env.Test_Project_Path }} --configuration Debug

      - name: Stop containers
        if: always()
        run: docker-compose -f ${{ env.Docker_Compose_Path }} down